export const mockUsers = [
  {
    id: 1,
    name: "Juan Pérez",
    email: "juan.perez@example.com",
    password: "123456",
    address: "Calle Falsa 123, Lima",
    phone: "987654321",
  },
  {
    id: 2,
    name: "María Gómez",
    email: "maria.gomez@example.com",
    password: "password123",
    address: "Av. Las Palmeras 456, Arequipa",
    phone: "912345678",
  },
  {
    id: 3,
    name: "Carlos Fernández",
    email: "carlos.fernandez@example.com",
    password: "qwerty789",
    address: "Jr. Los Olivos 789, Cusco",
    phone: "999111222",
  },
  {
    id: 4,
    name: "Lucía Ramírez",
    email: "lucia.ramirez@example.com",
    password: "lucia1234",
    address: "Calle Central 321, Trujillo",
    phone: "944333222",
  },
  {
    id: 5,
    name: "Andrés Salazar",
    email: "andres.salazar@example.com",
    password: "andrespass",
    address: "Pasaje Sur 222, Piura",
    phone: "933444555",
  },
];
